# Generated by Django 4.2.16 on 2026-05-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='milestone_type',
            field=models.CharField(choices=[('birth', '出生'), ('first_smile', '第一次微笑'), ('roll_over', '翻身'), ('sit', '坐'), ('crawl', '爬'), ('stand', '站立'), ('walk', '走路'), ('first_word', '叫妈妈/爸爸'), ('speak', '说话'), ('tooth', '长牙'), ('first_bite', '第一次吃辅食'), ('wean', '断奶'), ('first_step', '独立行走'), ('run', '跑步'), ('clap', '拍手'), ('wave', '挥手再见'), ('first_drawing', '第一幅画'), ('potty_train', '如厕训练'), ('kindergarten', '上幼儿园'), ('first_tooth_lost', '换牙'), ('ride_bike', '骑自行车'), ('swim', '游泳'), ('read', '自己看书'), ('other', '其他')], max_length=20),
        ),
    ]
